---
title: "Homework 6"
author: Ann Gould
github: gould-ann
output:
  html_document:
    df_print: paged
---

imports
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
```

read in data
```{r}
dog_info <- read_excel('dog.xlsx', sheet='Best in show full sheet', skip = 3)
# print(colnames(dog_info))

# clean
dog_info <- dog_info %>% rename('popularity' = `1- 173, 1 = most poular, US. American Kennel Club registrations 2011, pure breeds only`)

dog_info <- dog_info %>% rename('dog_info' = `American Kennel Club group`)
dog_info <- dog_info %>% rename('size_category' = `...32`)
dog_info <- dog_info %>% rename('popularity_rank' = `pure breeds, American Kennel Club 2011`)
dog_info <- dog_info %>% rename('intelligence_rank' = `...41`)
dog_info <- dog_info %>% rename('intelligence_percent' = `in descending rank (higher score = better),  normalized as percentage...12`)
dog_info <- dog_info %>% rename('score' = `intelligence + longevity + ailments + 50% (purchase price + food costs + grooming score). highest possible score: 4.5`)

# higher is better for intelligence percent
selected <- dog_info %>% select(`Dog breed`, `dog_info`, `popularity_rank`,`intelligence_rank`,`intelligence_percent`,`size_category`, `score`)

selected


```

Presenting the data
Y axis: popularity
X axis: data score
color: dog type
size of dog: size of dog
shape of dot?: if dog is smart or not
```{r}
# drop columns where there is no value on if a dog is smart or not 
selected <- selected[!is.na(selected$intelligence_percent), ]
# make a new column based off of value of if dog is smart or not
vals <- c()
for (val in selected$intelligence_percent){
  if (val > 0.5){
    vals <- c(vals, TRUE) 
  }
  else{
    vals <- c(vals, FALSE)
  }
}
selected$smart = vals

# make category a factor

as.factor(selected$dog_info)
as.factor(selected$size_category)
selected


```


I tried a lot to try to not have much overlap with this graph but had a lot of difficulty making the ggplot larger. 
```{r}
# options(repr.plot.width=15, repr.plot.height=8)

ggplot(selected,aes(x=score,y=-popularity_rank, color=dog_info, shape=smart, size=size_category)) + geom_point(alpha=.4) + geom_text(aes(label=`Dog breed`), alpha=0.6, size = 2) + ggtitle("Best in Show: The Ultimate Doggy Title") + xlab("Score") + ylab("Popularity")
```

